#!groovy

// Generated by IBM TransformationAdvisor
// Sat Mar 16 05:20:13 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'plantsbywebspherev8'
    mvnCommands = '--version'
    test='false'
}